### ISSUE TITLE
Mismatched define module when Shotgun is compiled using r.js

### ISSUE THREAD

**Issue by rgriffith** [jgnewman/shotgun#4]
Firstly, great work on the library!

I've been using Shotgun with RequireJS without a hitch; however, once I compile/bundle it with my other files using `r.js` I receive a mismatched define error:

```
Uncaught Error: Mismatched anonymous define() module: [object Object]
```

As soon as I remove Shotgun, the error goes away.

Any suggestions on how I can resolve this would be greatly appreciated.

**Comment by jgnewman** [comment]
@rgriffith I _think_ I've just fixed that problem. Would you mind pulling it again and trying it out?

**Comment by rgriffith** [comment]
@jgnewman just confirmed I'm not seeing the error anymore with the latest source. Unfortunately, I had to switch to using another library ([Mediator](https://github.com/ajacksified/Mediator.js)), but I am glad to hear I can switch back if needed.

Keep up the good work!
